<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1629859195440' stop='1629859409209'>
    <name>Create new project </name>
    <title>Create new project </title>
    <test-cases>
        <test-case start='1629859195784' status='failed' stop='1629859408978'>
            <name>Should create new project successfully.</name>
            <title>Should create new project successfully.</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='79180adf-ba9a-44b8-8267-daeda5f6e4f3-attachment.png' type='image/png' size='63630'/>
                <attachment title='Screenshot' source='ff6160f9-d86e-42f9-b60c-2cb8af430470-attachment.png' type='image/png' size='63630'/>
            </attachments>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at listOnTimeout (node:internal/timers:557:17)
                    at processTimers (node:internal/timers:500:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>