<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1629699586543' stop='1629699791665'>
    <name>Create new project </name>
    <title>Create new project </title>
    <test-cases>
        <test-case start='1629699586752' status='failed' stop='1629699791327'>
            <name>Should create new project successfully.</name>
            <title>Should create new project successfully.</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='82a3c77c-8047-40ac-9849-84d1a9432d63-attachment.png' type='image/png' size='59236'/>
                <attachment title='Screenshot' source='aae9c951-6a31-48c0-af55-ed5bf3d51044-attachment.png' type='image/png' size='59236'/>
            </attachments>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at listOnTimeout (node:internal/timers:557:17)
                    at processTimers (node:internal/timers:500:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>