<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1629274843570' stop='1629275143861'>
    <name>annotate project ...</name>
    <title>annotate project ...</title>
    <test-cases>
        <test-case start='1629274843826' status='failed' stop='1629275143859'>
            <name>Should annotate project with more than 6 labels successfully.</name>
            <title>Should annotate project with more than 6 labels successfully.</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='1f0b967d-5eec-4b08-9ada-f69cdeadffc1-attachment.png' type='image/png' size='57706'/>
                <attachment title='Screenshot' source='a24b57ff-19c3-43ca-9167-49ccea2e3f32-attachment.png' type='image/png' size='57706'/>
            </attachments>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at listOnTimeout (internal/timers.js:554:17)
                    at processTimers (internal/timers.js:497:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>