<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1629795217968' stop='1629795518550'>
    <name>Create new project </name>
    <title>Create new project </title>
    <test-cases>
        <test-case start='1629795218201' status='failed' stop='1629795518223'>
            <name>Should create log project successfully.</name>
            <title>Should create log project successfully.</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='c65e37ab-5217-40c8-9b87-b04b8508d32c-attachment.png' type='image/png' size='47957'/>
                <attachment title='Screenshot' source='3ad03b02-e2b2-4337-92b4-eb79701d2693-attachment.png' type='image/png' size='47957'/>
            </attachments>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at listOnTimeout (node:internal/timers:557:17)
                    at processTimers (node:internal/timers:500:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>