<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1629683960159' stop='1629685674066'>
    <name>annotate project ...</name>
    <title>annotate project ...</title>
    <test-cases>
        <test-case start='1629683960164' status='failed' stop='1629684166298'>
            <name>Should create and clear log project filter successfully.</name>
            <title>Should create and clear log project filter successfully.</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='49799cfb-f935-440f-9425-afc7683efa88-attachment.png' type='image/png' size='66354'/>
                <attachment title='Screenshot' source='e25372e1-e784-4406-b332-1cd1bd03ba4c-attachment.png' type='image/png' size='66354'/>
            </attachments>
            <failure>
                <message>WebDriverError: element click intercepted: Element &lt;a _ngcontent-goi-c1="" class="nav-link" href="/game" routerlinkactive="active">...&lt;/a> is not clickable at point (436, 30). Other element would receive the click: &lt;div _ngcontent-goi-c8="" class="modal">...&lt;/div>
                  (Session info: headless chrome=92.0.4515.159)
                  (Driver info: chromedriver=92.0.4515.107 (87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}),platform=Windows NT 10.0.19043 x86_64)</message>
                <stack-trace>WebDriverError: element click intercepted: Element &lt;a _ngcontent-goi-c1="" class="nav-link" href="/game" routerlinkactive="active">...&lt;/a> is not clickable at point (436, 30). Other element would receive the click: &lt;div _ngcontent-goi-c8="" class="modal">...&lt;/div>
                  (Session info: headless chrome=92.0.4515.159)
                  (Driver info: chromedriver=92.0.4515.107 (87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}),platform=Windows NT 10.0.19043 x86_64)
                    at Object.checkLegacyResponse (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\error.js:546:15)
                    at parseHttpResponse (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\http.js:509:13)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\http.js:441:30
                    at runMicrotasks (&lt;anonymous>)
                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
                From: Task: WebElement.click()
                    at Driver.schedule (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
                    at WebElement.schedule_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\webdriver.js:2010:25)
                    at WebElement.click (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\webdriver.js:2092:17)
                    at actionFn (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:89:44)
                    at Array.map (&lt;anonymous>)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:461:65
                    at ManagedPromise.invokeCallback_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:2927:27Error: 
                    at ElementArrayFinder.applyAction_ (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:459:27)
                    at ElementArrayFinder.&lt;computed> [as click] (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:91:29)
                    at ElementFinder.&lt;computed> [as click] (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:831:22)
                    at AnnotatePage.&lt;anonymous> (E:\vmware\Loop\GitHub\e2e\page-object\annotate-page.ts:77:25)
                    at Generator.next (&lt;anonymous>)
                    at fulfilled (E:\vmware\Loop\GitHub\e2e\node_modules\tslib\tslib.js:112:62)
                    at runMicrotasks (&lt;anonymous>)
                    at processTicksAndRejections (node:internal/process/task_queues:96:5)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1629684166298' status='failed' stop='1629684366516'>
            <name>Should wrap and clear wrap log project text successfully.</name>
            <title>Should wrap and clear wrap log project text successfully.</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='8d5fdb63-ae9d-4010-92a6-cc296ee1ff0c-attachment.png' type='image/png' size='66354'/>
            </attachments>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at listOnTimeout (node:internal/timers:557:17)
                    at processTimers (node:internal/timers:500:7)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1629684366518' status='failed' stop='1629684566807'>
            <name>Should annotate one row of log project successfully.</name>
            <title>Should annotate one row of log project successfully.</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='59ae6bb4-3c85-4e0f-affd-4fbbde180353-attachment.png' type='image/png' size='66354'/>
                <attachment title='Screenshot' source='d371f911-aa76-4da2-9624-ad3c570a1600-attachment.png' type='image/png' size='66354'/>
            </attachments>
            <failure>
                <message>TypeError: Cannot read property 'click' of undefined</message>
                <stack-trace>TypeError: Cannot read property 'click' of undefined
                    at AnnotatePage.&lt;anonymous> (E:\vmware\Loop\GitHub\e2e\page-object\annotate-page.ts:214:18)
                    at Generator.next (&lt;anonymous>)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\tslib\tslib.js:115:75
                    at new Promise (&lt;anonymous>)
                    at Object.__awaiter (E:\vmware\Loop\GitHub\e2e\node_modules\tslib\tslib.js:111:16)
                    at E:\vmware\Loop\GitHub\e2e\page-object\annotate-page.ts:213:52
                    at ManagedPromise.invokeCallback_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:2927:27</stack-trace>
            </failure>
        </test-case>
        <test-case start='1629684566807' status='failed' stop='1629684767019'>
            <name>Should delete one row of log project successfully.</name>
            <title>Should delete one row of log project successfully.</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='500ecea4-57ac-4a24-b26f-b77d217948e5-attachment.png' type='image/png' size='66354'/>
                <attachment title='Screenshot' source='b88cdfb0-2941-46d9-ad31-af68ce599ef7-attachment.png' type='image/png' size='66354'/>
            </attachments>
            <failure>
                <message>TypeError: Cannot read property 'click' of undefined</message>
                <stack-trace>TypeError: Cannot read property 'click' of undefined
                    at AnnotatePage.&lt;anonymous> (E:\vmware\Loop\GitHub\e2e\page-object\annotate-page.ts:223:18)
                    at Generator.next (&lt;anonymous>)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\tslib\tslib.js:115:75
                    at new Promise (&lt;anonymous>)
                    at Object.__awaiter (E:\vmware\Loop\GitHub\e2e\node_modules\tslib\tslib.js:111:16)
                    at E:\vmware\Loop\GitHub\e2e\page-object\annotate-page.ts:222:52
                    at ManagedPromise.invokeCallback_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:2927:27</stack-trace>
            </failure>
        </test-case>
        <test-case start='1629684767019' status='failed' stop='1629684967243'>
            <name>Should add row freeText successfully.</name>
            <title>Should add row freeText successfully.</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='5712e9b0-98e6-4d4d-bf0b-a83c9bc66e15-attachment.png' type='image/png' size='66354'/>
                <attachment title='Screenshot' source='7e5dc6a5-253c-4aa0-ae40-b13b66c9c6fc-attachment.png' type='image/png' size='66354'/>
            </attachments>
            <failure>
                <message>TypeError: Cannot read property 'click' of undefined</message>
                <stack-trace>TypeError: Cannot read property 'click' of undefined
                    at AnnotatePage.&lt;anonymous> (E:\vmware\Loop\GitHub\e2e\page-object\annotate-page.ts:231:21)
                    at Generator.next (&lt;anonymous>)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\tslib\tslib.js:115:75
                    at new Promise (&lt;anonymous>)
                    at Object.__awaiter (E:\vmware\Loop\GitHub\e2e\node_modules\tslib\tslib.js:111:16)
                    at E:\vmware\Loop\GitHub\e2e\page-object\annotate-page.ts:230:64
                    at ManagedPromise.invokeCallback_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:2927:27</stack-trace>
            </failure>
        </test-case>
        <test-case start='1629684967243' status='failed' stop='1629685167441'>
            <name>Should add log freeText successfully.</name>
            <title>Should add log freeText successfully.</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='3929c39e-8f50-4e59-b0e4-5f7975fea3bc-attachment.png' type='image/png' size='66354'/>
            </attachments>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at listOnTimeout (node:internal/timers:557:17)
                    at processTimers (node:internal/timers:500:7)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1629685167442' status='failed' stop='1629685467738'>
            <name>Should submit and skip and flag log annotation successfully.</name>
            <title>Should submit and skip and flag log annotation successfully.</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='c36e641e-97b4-423a-939d-a1ab96adb04b-attachment.png' type='image/png' size='66354'/>
                <attachment title='Screenshot' source='51fbdf33-9fb8-4344-a1d7-4b2c7cbe54d8-attachment.png' type='image/png' size='66354'/>
            </attachments>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at listOnTimeout (node:internal/timers:557:17)
                    at processTimers (node:internal/timers:500:7)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1629685467741' status='failed' stop='1629685674064'>
            <name>Should review log project successfully.</name>
            <title>Should review log project successfully.</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='de40671f-e5ee-4b2a-ad8c-fcac9e164475-attachment.png' type='image/png' size='66354'/>
                <attachment title='Screenshot' source='5fde8445-b6fb-409e-bb52-752f78cf1630-attachment.png' type='image/png' size='66354'/>
            </attachments>
            <failure>
                <message>WebDriverError: element click intercepted: Element &lt;a _ngcontent-goi-c1="" class="nav-link" href="/game" routerlinkactive="active">...&lt;/a> is not clickable at point (436, 30). Other element would receive the click: &lt;div _ngcontent-goi-c8="" class="modal">...&lt;/div>
                  (Session info: headless chrome=92.0.4515.159)
                  (Driver info: chromedriver=92.0.4515.107 (87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}),platform=Windows NT 10.0.19043 x86_64)</message>
                <stack-trace>WebDriverError: element click intercepted: Element &lt;a _ngcontent-goi-c1="" class="nav-link" href="/game" routerlinkactive="active">...&lt;/a> is not clickable at point (436, 30). Other element would receive the click: &lt;div _ngcontent-goi-c8="" class="modal">...&lt;/div>
                  (Session info: headless chrome=92.0.4515.159)
                  (Driver info: chromedriver=92.0.4515.107 (87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}),platform=Windows NT 10.0.19043 x86_64)
                    at Object.checkLegacyResponse (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\error.js:546:15)
                    at parseHttpResponse (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\http.js:509:13)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\http.js:441:30
                    at runMicrotasks (&lt;anonymous>)
                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
                From: Task: WebElement.click()
                    at Driver.schedule (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
                    at WebElement.schedule_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\webdriver.js:2010:25)
                    at WebElement.click (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\webdriver.js:2092:17)
                    at actionFn (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:89:44)
                    at Array.map (&lt;anonymous>)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:461:65
                    at ManagedPromise.invokeCallback_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:2927:27Error: 
                    at ElementArrayFinder.applyAction_ (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:459:27)
                    at ElementArrayFinder.&lt;computed> [as click] (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:91:29)
                    at ElementFinder.&lt;computed> [as click] (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:831:22)
                    at AnnotatePage.&lt;anonymous> (E:\vmware\Loop\GitHub\e2e\page-object\annotate-page.ts:77:25)
                    at Generator.next (&lt;anonymous>)
                    at fulfilled (E:\vmware\Loop\GitHub\e2e\node_modules\tslib\tslib.js:112:62)
                    at runMicrotasks (&lt;anonymous>)
                    at processTicksAndRejections (node:internal/process/task_queues:96:5)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>