<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1629252059256' stop='1629252359602'>
    <name>Create new project </name>
    <title>Create new project </title>
    <test-cases>
        <test-case start='1629252059378' status='failed' stop='1629252359404'>
            <name>Should create log project successfully.</name>
            <title>Should create log project successfully.</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='87de697f-a308-45d5-ad3b-fb5eaa21f2db-attachment.png' type='image/png' size='58856'/>
                <attachment title='Screenshot' source='4b021438-4fd0-43ae-9ca9-a9d4f66490ed-attachment.png' type='image/png' size='58856'/>
            </attachments>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at listOnTimeout (internal/timers.js:554:17)
                    at processTimers (internal/timers.js:497:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>