<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1629690364729' stop='1629690568059'>
    <name>Create new project </name>
    <title>Create new project </title>
    <test-cases>
        <test-case start='1629690364868' status='failed' stop='1629690567826'>
            <name>Should create new project successfully.</name>
            <title>Should create new project successfully.</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='e8befd53-cec7-4d7e-b081-073a8a06df4e-attachment.png' type='image/png' size='59232'/>
                <attachment title='Screenshot' source='aa0af3ed-4126-40e7-816b-c62e0bafb370-attachment.png' type='image/png' size='59232'/>
            </attachments>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at listOnTimeout (node:internal/timers:557:17)
                    at processTimers (node:internal/timers:500:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>